<%*		
try { 
    // let numReferencia = tp.user.generarNumReferencia(dv);
    // await tp.user.generarCita(tp, numReferencia) 
    
    // numReferencias.push(numReferencia);
} catch (_) { 
    const mensaje = "Hubo un error al agregar la referencia";
    
    console.log(mensaje);
    new Notice(mensaje);
}
_%>